# Generated by Django 2.2.4 on 2019-08-19 21:55

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineralData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image_filename', models.CharField(max_length=255, unique=True)),
                ('image_caption', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('group', models.CharField(max_length=500)),
                ('formula', models.CharField(blank=True, default='', max_length=500)),
                ('strunz_classification', models.CharField(blank=True, default='', max_length=500)),
                ('crystal_system', models.CharField(blank=True, default='', max_length=500)),
                ('unit_cell', models.CharField(blank=True, default='', max_length=500)),
                ('color', models.CharField(blank=True, default='', max_length=500)),
                ('crystal_symmetry', models.CharField(blank=True, default='', max_length=500)),
                ('cleavage', models.CharField(blank=True, default='', max_length=500)),
                ('mohs_scale_hardness', models.CharField(blank=True, default='', max_length=500)),
                ('luster', models.CharField(blank=True, default='', max_length=500)),
                ('streak', models.CharField(blank=True, default='', max_length=500)),
                ('diaphaneity', models.CharField(blank=True, default='', max_length=500)),
                ('optical_properties', models.CharField(blank=True, default='', max_length=500)),
                ('refractive_index', models.CharField(blank=True, default='', max_length=500)),
                ('crystal_habit', models.CharField(blank=True, default='', max_length=500)),
                ('specific_gravity', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': [django.db.models.functions.text.Lower('name')],
            },
        ),
        migrations.AddIndex(
            model_name='mineraldata',
            index=models.Index(fields=['name'], name='minerals_ap_name_c3cd1e_idx'),
        ),
    ]
