# Generated by Django 2.2.4 on 2019-08-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MineralData',
            new_name='Mineral',
        ),
        migrations.RemoveIndex(
            model_name='mineral',
            name='minerals_ap_name_c3cd1e_idx',
        ),
        migrations.AddIndex(
            model_name='mineral',
            index=models.Index(fields=['name'], name='minerals_ap_name_bc4492_idx'),
        ),
    ]
